[package]
name = "rs621"
version = "0.6.0"
authors = ["nasso <nassomails@gmail.com>"]
edition = "2018"
description = "Rust crate for the E621 API (a large online archive of furry art)."
repository = "https://github.com/nasso/rs621"
readme = "README.md"
keywords = ["e621", "e926", "furry", "api", "client"]
categories = ["api-bindings"]
license = "MIT OR Apache-2.0"

[badges]
travis-ci = { repository = "nasso/rs621" }
codecov = { repository = "nasso/rs621" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.7.1"
urlencoding = "1.0.0"
chrono = "0.4.11"
serde_json = "1.0.55"
futures = "0.3"

[dependencies.reqwest]
version = "0.10.6"
features = ["json"]

[dev-dependencies]
mockito = "0.23.3"

[dev-dependencies.tokio]
version = "0.2.21"
features = ["rt-threaded", "macros"]
