[package]
name = "rs621"
version = "0.1.0"
authors = ["nasso <nassomails@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
serde_json = "1.0.40"
reqwest_mock = { path = "reqwest_mock" }
